# -*- coding: utf-8 -*-
"""E-Commerce Web Scraping & Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYqWD31h1rLeIOXal8HBR0V_MLb7yKKX
"""

!pip install requests beautifulsoup4

# Import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt

# Base URL for scraping
base_url = "http://books.toscrape.com/catalogue/page-{}.html"

# Lists to store scraped data
book_names = []
prices = []
ratings = []
availability = []

# Scrape first 5 pages
for page in range(1, 6):
    url = base_url.format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:
        book_names.append(book.h3.a["title"])
        prices.append(book.find("p", class_="price_color").text)
        ratings.append(book.find("p")["class"][1])
        availability.append(book.find("p", class_="instock availability").text.strip())

# Create DataFrame
df = pd.DataFrame({
    "Book_Name": book_names,
    "Price": prices,
    "Rating": ratings,
    "Availability": availability
})

# Data Cleaning
# Using regex to remove any non-numeric characters (like Â or £) except the decimal point
df["Price"] = df["Price"].str.replace(r"[^0-9.]", "", regex=True).astype(float)

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}
df["Rating"] = df["Rating"].map(rating_map)

# Data Overview
print("Dataset Info:")
df.info()

print("\nSummary Statistics:")
print(df.describe())

# Example: Installing the 'seaborn' library
!pip install seaborn

# Business Analysis
print("\nAverage Price:", round(df["Price"].mean(), 2))
print("Average Rating:", round(df["Rating"].mean(), 2))

# Visualization - Rating Distribution
df["Rating"].value_counts().sort_index().plot(kind="bar", title="Book Rating Distribution")
plt.xlabel("Rating")
plt.ylabel("Number of Books")
plt.show()

# Visualization - Price Distribution
df["Price"].plot(kind="hist", bins=10, title="Price Distribution of Books")
plt.xlabel("Price")
plt.show()

# Availability Analysis
print("\nAvailability Count:")
print(df["Availability"].value_counts())

# Save dataset
df.to_csv("ecommerce_books_scraped_data.csv", index=False)
print("\nDataset saved as ecommerce_books_scraped_data.csv")

